# Generated by Django 5.2.5 on 2025-08-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('scatter', 'Scatter Plot'), ('histogram', 'Histogram'), ('box', 'Box Plot'), ('heatmap', 'Heatmap'), ('correlation', 'Correlation Matrix'), ('confusion_matrix', 'Confusion Matrix'), ('roc_curve', 'ROC Curve'), ('precision_recall', 'Precision-Recall Curve'), ('feature_importance', 'Feature Importance')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingestion.dataset')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeling.modelevaluation')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeling.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('data_analysis', 'Data Analysis'), ('preprocessing', 'Preprocessing'), ('model_evaluation', 'Model Evaluation'), ('model_comparison', 'Model Comparison'), ('comprehensive', 'Comprehensive')], max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('charts', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingestion.dataset')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeling.modelevaluation')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeling.mlmodel')),
            ],
        ),
    ]
